In [3]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [183]:
2**np.arange(1, 21) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [184]:
np.sum(np.ones(6)/10 ** (np.arange(6) * 3) * np.ones(6)/5 ** (np.arange(6) * 4))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [185]:
(1 + np.arange(8) + np.arange(8).reshape(8, 1))%2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [186]:
X = np.random.random((5, 2))
X
np.array((np.sqrt(np.sum(X**2, axis=1)), np.arccos(X[:, 0] / np.sqrt(np.sum(X**2, axis=1)))), dtype=np.float).T

array([[0.80326252, 1.37172701],
       [1.15471767, 0.53061302],
       [0.72409257, 0.55592314],
       [1.01676463, 0.61914919],
       [0.42687496, 1.51141709]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [187]:
X = np.random.random((10, 10))
X
## your code

array([[0.70747645, 0.72858461, 0.18523571, 0.8236423 , 0.46466689,
        0.41977512, 0.02050808, 0.02017988, 0.95111546, 0.47897963],
       [0.25319713, 0.25727348, 0.23107215, 0.67651228, 0.39088158,
        0.52242691, 0.50789856, 0.98306937, 0.490239  , 0.20485016],
       [0.77979159, 0.65945136, 0.22360155, 0.75432185, 0.22418392,
        0.83142535, 0.79459335, 0.0254855 , 0.40426165, 0.64514244],
       [0.21441004, 0.23662843, 0.40755128, 0.40178041, 0.73303589,
        0.83274675, 0.54062885, 0.39216638, 0.54964718, 0.42218598],
       [0.073385  , 0.95804386, 0.93235963, 0.42101395, 0.33910077,
        0.3034472 , 0.80054628, 0.23675969, 0.18001533, 0.30737349],
       [0.12890094, 0.26277177, 0.46964405, 0.37053615, 0.8089143 ,
        0.54611569, 0.88006679, 0.46753988, 0.27404632, 0.52559055],
       [0.10159359, 0.64671015, 0.1196782 , 0.9638094 , 0.90790211,
        0.58827942, 0.2102562 , 0.8847261 , 0.74598833, 0.36931082],
       [0.83064301, 0.51538529, 0.3876348

In [188]:
np.argmax(X)//10, np.argmax(X)%10

(1, 7)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [189]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

X[np.sqrt(np.sum((X-y)**2, axis=1)).argmin()]

array([0.62287517, 0.04849169])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [190]:
## your code
## your code
f = lambda x: [ x**2 + 2*x + 6,
                x + 6,
                x**2 + 4*x - 4 
              ]
np.sum(np.array(
    [np.arange(-3, 3.1, 0.1)<0, (np.arange(-3, 3.1, 0.1)>=0)*(np.arange(-3, 3.1, 0.1)<=2), 
     np.arange(-3, 3.1, 0.1)>2],dtype=int
    ) *  np.array(f(np.arange(-3, 3.1, 0.1))), axis=0)

array([ 9.  ,  8.61,  8.24,  7.89,  7.56,  7.25,  6.96,  6.69,  6.44,
        6.21,  6.  ,  5.81,  5.64,  5.49,  5.36,  5.25,  5.16,  5.09,
        5.04,  5.01,  5.  ,  5.01,  5.04,  5.09,  5.16,  5.25,  5.36,
        5.49,  5.64,  5.81,  6.  ,  6.1 ,  6.2 ,  6.3 ,  6.4 ,  6.5 ,
        6.6 ,  6.7 ,  6.8 ,  6.9 ,  7.  ,  7.1 ,  7.2 ,  7.3 ,  7.4 ,
        7.5 ,  7.6 ,  7.7 ,  7.8 ,  7.9 ,  8.  ,  8.81,  9.64, 10.49,
       11.36, 12.25, 13.16, 14.09, 15.04, 16.01, 17.  ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [191]:
X = np.random.random((10, 10))
X - np.mean(X,axis = 1).reshape((10,1))

array([[ 0.3706605 , -0.37956927,  0.33910093,  0.14154677, -0.42563248,
        -0.03800942, -0.38181513,  0.41306435,  0.07735345, -0.11669971],
       [ 0.00722344, -0.37362849, -0.12265931, -0.38845552, -0.1161233 ,
        -0.07764718,  0.34213355, -0.153714  ,  0.44488493,  0.43798588],
       [ 0.20790529, -0.23393569,  0.33561571, -0.13626764,  0.04251749,
        -0.16710664,  0.03500549, -0.48329753,  0.02023181,  0.37933172],
       [-0.46465536, -0.24148949,  0.01193622,  0.15614661,  0.51591795,
        -0.12019668, -0.16296555,  0.13441296, -0.3400133 ,  0.51090663],
       [-0.08294599,  0.3312297 ,  0.36417389, -0.28602912,  0.14329507,
         0.52243385, -0.19461726, -0.36097173, -0.10743695, -0.32913147],
       [ 0.10340844,  0.10270644, -0.27932094, -0.1271594 ,  0.15188908,
         0.15256087,  0.02472444, -0.29599565, -0.31797356,  0.48516027],
       [-0.15521222,  0.21858617,  0.03839668,  0.62259429, -0.10778319,
        -0.3068644 ,  0.16358662, -0.31219045

In [192]:
# Проверка
np.sum(X - np.mean(X,axis = 1).reshape((10,1)), axis=-1)

array([-5.55111512e-16,  0.00000000e+00, -3.33066907e-16,  6.66133815e-16,
       -4.44089210e-16, -3.33066907e-16,  2.22044605e-16, -1.11022302e-16,
        4.44089210e-16, -5.55111512e-16])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [193]:
X = np.random.normal(loc=5, scale=2., size=1000)
m = np.sum(X)/1000
D = np.sum((X - m)**2)/1000
m, D

(5.074171231424645, 4.337322958847219)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [194]:
(np.arange(5)+np.arange(5).reshape(5,1))%5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])